name: ogzaf-dev
channels:
- conda-forge
dependencies:
- python>=3.7.7, <=3.11  # This restriction can be removed as soon as these packages support Python 3.10
- ipython
- setuptools
- psutil
- openssl=1.1.1  # This is a requirement of the UN data portal which we are using in demographics.py
- numpy<=1.21.2  # This restriction can be removed as soon as Numba supports NumPy 1.22
- scipy>=1.7.1
- pandas>=1.2.5
- matplotlib
- dask>=2.30.0
- dask-core>=2.30.0
- distributed>=2.30.1
- paramtools>=0.15.0
- sphinx>=3.5.4
- sphinx-book-theme>=0.1.3
- pip
- pytest>=6.0
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- requests
- xlwt
- openpyxl
- statsmodels
- linearmodels
- black
- jupyter
- pip:
  - jupyter-book>=0.9.1
  - pandas-datareader
  - ogcore
