name: ogzaf-dev
channels:
- conda-forge
dependencies:
- python>=3.7.7, <=3.9.12  # This restriction can be removed as soon as these packages support Python 3.10
#- mkl>=2020.2  ## this fails on M1 Mac: "ResolvePackageNotFound:  - mkl[version='>=2020.2']"
- numpy<=1.21.2  # This restriction can be removed as soon as Numba supports NumPy 1.22
- psutil
- scipy>=1.5.0
- pandas>=1.2.5
- matplotlib
- dask>=2.30.0
- dask-core>=2.30.0
- distributed>=2.30.1
- paramtools>=0.15.0
- sphinx>=3.5.4
- sphinx-book-theme>=0.1.3
- pip
- pytest>=6.0
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- requests
- xlwt
- openpyxl
- statsmodels
- linearmodels
- black
- pip:
  - jupyter-book>=0.9.1
  - pandas-datareader
  #- ogcore
